http:
  routers:
    to_redirect:
      entryPoints: web
      middlewares:
        - "www-redirect"
      service: odoo_service
      rule: "PathPrefix(`/`)"

    to_redirect2:
      entryPoints: web-secure
      middlewares:
        - "www-redirect"
      service: odoo_service
      rule: "Host(`www.pir.lt`)"
      tls:
        domains:
        - "www.pir.lt"
        certResolver: le

    to_odoo_secure:
      entryPoints: web-secure
      service: odoo_service
      rule: "Host(`pir.lt`)"
      tls:
        domains: 
        - "pir.lt"
        certResolver: le

    to_odoo_longpolling_secure:
      entryPoints: web-secure
      service: odoo_longpolling
      rule: "PathPrefix(`/longpolling`)"
      tls:
        domains: 
        - "pir.lt"
        certResolver: le

  services:
    odoo_service:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:8069/"

    odoo_longpolling:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:8072/"

  middlewares:
    www-redirect:
      redirectRegex:
        regex: "^https?://(www.)?pir.lt(.*)"
        replacement: "https://pir.lt"
        permanent: true

